### PR TITLE
[WIP]Add markdown dialog in edit page

### PR DESCRIPTION
**Pull request by kyow**
todo
- [ ] internationalization

### CODE REVIEW

**Comment by nanonanomachine** [comment]
It seems good  to create  a new partial view file for help dialog.

**Comment by nanonanomachine** [comment]
I'll check it later today and fight with previous PR, thanks for many good contribution!

**Comment by nanonanomachine** [comment]
Testing with Chrome. Looks so great...!

image

Have you ever been tested several browser? e.g., Firefox, IE?

**Comment by nanonanomachine** [comment]
There's no problem with OSX browsers, Firefox 43.0.2, Safari 9.0.2.

**Comment by kyow** [comment]
I tested with only Chrome in OSX and Win.
So, I just tried IE11 in Win8.1.

_010316_020044_pm

It seems no problem.

**Comment by nanonanomachine** [comment]
@kyow I think it's better to use `水平線` instead of `(水平線)` at horizontal line section because the parenthesis means nothing for me. What do you think?

**Comment by nanonanomachine** [comment]
Recreate PR. See #37 .

**Pull request closed without merging**
